server:
  port: 6444
  
logging.level:
  tw.sanjiheart: DEBUG
  
kube:
  # change to Kubernetes API endpoint
  url: https://192.168.1.40:6443
  # change to Kubernetes token
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLXBrZnZ2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwNDUzMWYyYi03MzA2LTExZTktOWMzZC0wODAwMjdjYTU1MjUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.V122fsA9mZJ7XRIiTbMI1mBKHoTTR4e-987HHf-THUh7I4HuXkSUD8FbGe_yOkvG7_WEB-CMXkkWdCqn5aJbnSsC4hCNtyeZFm7_zUeByPS1M9bKhFEAivemddxdbx_cIu7UGyhbuOiNZ1gUoXiYORsnJUxKS-_TSqMoO7BokhdT9aH2X3pA4euqxpd1nWXk5t-43c1EhVJkF_1XdJ-jjfk7Q0B0DE2iyiWqQaBKPwMp7QLTdKQX4qMbMtIbbcpR6Rtd_gPi_2HDUwL5oL2kpoLml1K9w9Tj4JqZ4rxuJZW0poUbJFJF-bsjS5wFj7zS-mOd-XehuAVxS1ln4VdfxQ
  validateSSL: false